spring:
  datasource:
    url: jdbc:mysql://localhost:3306/eduplus_db
    username: root
    password: ""

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  servlet:
    multipart:
      max-file-size: 2MB
      max-request-size: 2MB

app:
  jwt:
    secret: u8wrvgTsRLgGQcZdiOXKGc6KmSfNX/1Fch12r7uRchJEOzOiJZhFnflBWJ/HykgH5UQeBJI+wRD44Tb34X4WAw==
    expiration: 86400000
    access-token-expiration: 900000
    refresh-token-expiration: 604800000
  upload:
    dir: uploads/

server:
  port: 8080
